name: "Naru's WRX"
favicon: null
layout_spectrum: 0.761217069812119
typography_spectrum: 0.8486846999730915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#67646d'
    - '#ffffff'
    - '#a29ba2'
    - '#494039'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.377662610495463
purpose: []
