name: Naru
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#0a778e'
    - '#43aed8'
    - '#bcdce9'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
