name: Naru
favicon: null
layout_spectrum: 0.24998
typography_spectrum: 0.49137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5e6f7'
    - '#a19d94'
    - '#1a1e29'
    - '#5474a5'
    - '#9bc5c1'
  brandStrength: 0.5
  lightness: 0.506114
  saturation: 0.5
  rhythmicContrast: 0.61413
purpose: []
