analytics: {}
color:
  brandColors:
    - '#C0C8C0'
    - '#622330'
    - '#5088A0'
    - '#C05068'
    - '#D0D098'
  brandStrength: 1
  lightness: 0.506114
  rhythmicContrast: 0.61413
  saturation: 0.700408
cta: {}
layout_spectrum: 0
name: Naru
opengraph: {}
purpose: []
typography_spectrum: 0.11558
